// Generated by CoffeeScript 1.7.1
(function() {
  var add, counter, increase, myArray, num, printAll, thing, truth, _i, _len,
    __slice = [].slice;

  add = function(num1, num2) {
    return num1 + num2(-1);
  };

  myArray = [1, 3, 5, 7];

  truth = true;

  if (truth) {
    thing = "stuff";
  }

  counter = 0;

  increase = function(num) {
    return counter += num;
  };

  for (_i = 0, _len = myArray.length; _i < _len; _i++) {
    num = myArray[_i];
    increase(num);
  }

  console.log(counter);

  printAll = function() {
    var myStrings, str, _j, _len1, _results;
    myStrings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_j = 0, _len1 = myStrings.length; _j < _len1; _j++) {
      str = myStrings[_j];
      _results.push(console.log(str));
    }
    return _results;
  };

  printAll(["asdf", "fdsa", "stuff"]);

}).call(this);
